создал 3,1
Anaksimander/nsu-sdt2020 pull request #2
Opened 2020-10-27 12:22 UTC by Anaksimander

2020-10-27 13:52 UTC, shishkin-pavel requested changes

2020-10-27 13:52 UTC, shishkin-pavel commented on laba3/laba3_1.clj
> +         (map #(future (heavy-inc %)) (main coll size_bloc)))))))
кажется, оно не должно работать быстрее обычного фильтра, это так?
если да, то в чём проблема и как исправлять?

2020-10-30 22:17 UTC, shishkin-pavel reviewed
это ок, теперь в этом же ревью давай 3.2

2020-10-30 22:17 UTC, shishkin-pavel commented on laba3/laba3_1.clj
> +   (map #(future (doall (filter (heavy 100 pred) %))))
я говорил, что вместо `(heavy 100 pred)` тут хочется видеть просто `pred`

2020-11-03 09:14 UTC, Anaksimander commented
my-filter-batch (coll размер_чанка размер_батча предикат)
вот такое он кушает)

2020-11-06 11:23 UTC, shishkin-pavel requested changes

2020-11-06 11:23 UTC, shishkin-pavel commented on laba3/laba3_1.clj
> +  (let [pred (heavy 100 pred-i)]
зачем делать любой предикат тяжёлым? тут стоит просто использовать переданный, а _в месте вызова_ передавать тяжёлый

2020-11-06 11:23 UTC, shishkin-pavel commented on laba3/laba3_2.clj
> +  (time (my-filter-batch '(1 2 3 4 5 6 7 8 9 10) 2 4 even?))
как минимум не работает с бесконечными последовательностями

2020-11-10 04:13 UTC, Anaksimander commented
Если вы забыли что просили меня исправить (на паре), то это
- задавать размер батча чанками ( size =3 - 3 чанка). а не элементами
- работа с бесконечными последовательностями

2020-11-14 03:47 UTC, shishkin-pavel approved these changes

2020-11-14 03:48 UTC, merged